"""Review phase contract.

Centralizes the canonical phase string and the expected
status/state vocabulary. Any artifact that records a phase MUST
import the phase from this module so the Terminal Seal can derive
phase from package contents rather than CLI injection.
"""

from __future__ import annotations

BASE_PHASE = "COMMUNIS-CUSTOMOS-BOOTSTRAP-P1-P2-R7"
ACTIVE_REPAIR_CYCLE = "CR4"
PHASE = f"{BASE_PHASE}-{ACTIVE_REPAIR_CYCLE}"

CANDIDATE_STATUS_READY = "READY_FOR_INDEPENDENT_REVIEW"
CANDIDATE_STATUS_NOT_READY = "NOT_READY_FOR_INDEPENDENT_REVIEW"

INDEPENDENT_REVIEW_PENDING = "PENDING"
INDEPENDENT_REVIEW_ACCEPT = "ACCEPT"
INDEPENDENT_REVIEW_REJECT = "REJECT"

GATE_PASS = "PASS"
GATE_FAIL = "FAIL"

ALL_GATE_STATES = (GATE_PASS, GATE_FAIL)
ALL_INDEPENDENT_REVIEW_STATES = (
    INDEPENDENT_REVIEW_PENDING,
    INDEPENDENT_REVIEW_ACCEPT,
    INDEPENDENT_REVIEW_REJECT,
)
ALL_CANDIDATE_STATUSES = (
    CANDIDATE_STATUS_READY,
    CANDIDATE_STATUS_NOT_READY,
)

__all__ = [
    "ACTIVE_REPAIR_CYCLE",
    "ALL_CANDIDATE_STATUSES",
    "ALL_GATE_STATES",
    "ALL_INDEPENDENT_REVIEW_STATES",
    "BASE_PHASE",
    "CANDIDATE_STATUS_NOT_READY",
    "CANDIDATE_STATUS_READY",
    "GATE_FAIL",
    "GATE_PASS",
    "INDEPENDENT_REVIEW_ACCEPT",
    "INDEPENDENT_REVIEW_PENDING",
    "INDEPENDENT_REVIEW_REJECT",
    "PHASE",
]
